name: Linting with Ruff

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff-formatting:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5.6
        with:
          python-version: "3.9"
          cache: 'pip'
      - name: Install Ruff
        run: |
            pip install poetry
            poetry install --all-groups
      - name: Lint with Ruff
        run: |
          poetry run ruff check
      - name: Check for unformatted files
        run: |
          poetry run ruff format --check
